name: featurenodejspipeline
on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      component:
        required: true
        type: string
      environment:
        required: true
        type: string
env:
  ACCID: "634758830486"
jobs:
  featurenodejspipeline:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: list files
        run: ls -l 

      - name: Show workflow inputs
        run: |
          echo "Project: ${{ inputs.project }}"

      - name: Set appversion
        run: |
          APPVERSION="${GITHUB_SHA::7}"
          echo "APPVERSION=$APPVERSION" >> "$GITHUB_ENV"
          echo "App Version: $APPVERSION"

      - name: install dependencies
        id: npm_install
        run: npm install

      - name: Update Commit Status
        if: always() && steps.npm_install.outcome != 'skipped'
        uses: hemanchandra-devops/workflows/.github/actions/set-commit-status@main
        with:
          context: 'NPM Install'
          state: ${{ steps.npm_install.outcome == 'success' && 'success' || 'failure' }}
          description: ${{ steps.npm_install.outcome == 'success' && 'success' || 'failure' }}

      - name: unit tests
        run: echo "unit tests"

      - name: Check Dependabot Alerts
        env:
          TOKEN: ${{ secrets.TOKEN }}
          API_URL: "https://api.github.com/repos/hemanchandra-devops/catalogue-ci/dependabot/alerts?state=open&per_page=100"
        run: |
          set -e

          echo "Checking Dependabot alerts..."

          HTTP_STATUS=$(curl -sS \
            -o dependabot-alerts.json \
            -w "%{http_code}" \
            -H "Authorization: Bearer ${TOKEN}" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "${API_URL}")

          if [ "$HTTP_STATUS" -ne 200 ]; then
            echo "❌ Failed to retrieve Dependabot alerts."
            echo "GitHub API returned HTTP status: $HTTP_STATUS"
            cat dependabot-alerts.json
            exit 1
          fi

          echo "Dependabot API response:"
          jq '.' dependabot-alerts.json

          COUNT=$(jq '
            map(
              select(
                .state == "open" and
                (
                  .security_advisory.severity == "high" or
                  .security_advisory.severity == "critical"
                )
              )
            ) | length
          ' dependabot-alerts.json)

          echo "Open High/Critical Dependabot alerts: ${COUNT}"

          if [ "$COUNT" -gt 0 ]; then
            echo "❌ Pipeline FAILED"
            echo "Open High/Critical Dependabot vulnerabilities found."
            exit 1
          else
            echo "✅ No Open High/Critical Dependabot alerts."
            echo "Continuing pipeline..."
          fi

      - name: image build
        run: docker build -t ${ACCID}.dkr.ecr.us-east-1.amazonaws.com/${{ inputs.project }}/${{ inputs.component }}:$APPVERSION .

      - name: Trivy Scan
        run: |
          IMAGE="${ACCID}.dkr.ecr.us-east-1.amazonaws.com/${{ inputs.project }}/${{ inputs.component }}:${APPVERSION}"

          echo "Scanning image:"
          echo "$IMAGE"

          trivy image \
            --scanners vuln \
            --vuln-type os \
            --severity HIGH,CRITICAL \
            --exit-code 1 \
            "$IMAGE"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      - name: push image
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${ACCID}.dkr.ecr.us-east-1.amazonaws.com
          docker push ${ACCID}.dkr.ecr.us-east-1.amazonaws.com/${{ inputs.project }}/${{ inputs.component }}:$APPVERSION